### ISSUE TITLE
similar research

### ISSUE THREAD

**Issue by nlitsme** [nickbouwhuis/Albert-Heijn-OpenAPI#1]
Hi, 

I did something similar,  wanting to find which supermarket has the best discount at the moment.

https://gist.github.com/nlitsme/0abc1b8cb8af5c74aaace41576964bdf

note that the plus currently does not work.  initially my ip got blocked, so now using google-translate to get the search results.
but apparently the html formatting changed.

willem

**Comment by NickBouwhuis** [comment]
Very cool. Thanks for sharing

**Comment by Mvne** [comment]
Does one of you know whether there's an endpoint available to get my deliveries (mijn bestellingen)? I would like to get better insights in what i order most. I know there's an endpoint for receipts but that is only for shop purchases. Thank you!

**Comment by NickBouwhuis** [comment]
Hi!

Albert Heijn switched to GraphQL based queries for the most part. So my OpenApi docs are a bit outdated. 

But, I observed this call being made when clicking the orders button. The call is made to https://api.ah.nl/graphql

```json
{
  "operationName": "FetchOrdersOverview",
  "query": "query FetchOrdersOverview($status: FulfillmentStatus, $size: Int) { orderFulfillments(status: $status, size: $size) { __typename result { __typename orderId delivery { __typename deliveryMessage method slot { __typename date } status } cancellable reopenable orderMethod isSubscriptionOrder totalPrice { __typename totalPrice { __typename amount } } } } }",
  "variables": {
    "size": 25,
    "status": "OPEN"
  }
} 
```

**Comment by Mvne** [comment]
Thanks for your reply. I'll have a look at this.
